const BASE_ROUND_BONUS = 75;
const BASE_STRATAGEM_COUNT = 6;
const BASE_ROUND_DURATION = 1000 * 10; // 10 seconds
const STRATAGEM_COMPLETION_BONUS_PER_KEY = 86; // 86 ms per key
const TIME_BETWEEN_ROUNDS = 300; // 300 ms
const PERFECT_ROUND_BONUS = 100;
const FOLLOWING_ROUND_BONUS_ADDITION = 25;
const SHOW_ROUND_STATS_DURATION = 4000;
const CRITICAL_TIME_LEFT = 2000;
const GET_READY_DURATION = 3000;
const FINISHED_SCREEN_DURATION = 5000;
const TIME_INTERVAL_DECREMENT = 16;
export {
  BASE_ROUND_BONUS,
  BASE_STRATAGEM_COUNT,
  BASE_ROUND_DURATION,
  STRATAGEM_COMPLETION_BONUS_PER_KEY,
  TIME_BETWEEN_ROUNDS,
  PERFECT_ROUND_BONUS,
  FOLLOWING_ROUND_BONUS_ADDITION,
  SHOW_ROUND_STATS_DURATION,
  CRITICAL_TIME_LEFT,
  GET_READY_DURATION,
  FINISHED_SCREEN_DURATION,
  TIME_INTERVAL_DECREMENT,
};
